### ISSUE TITLE
Needs HTTPS support

### ISSUE THREAD

**Issue by babldev** [IrvineUniversityParkLibraryFriends/irvineuniversityparklibraryfriends.github.io#4]

**Comment by zackhsi** [comment]
Pull requests welcome!

**Comment by zackhsi** [comment]
<img width="423" alt="screen shot 2017-05-29 at 11 36 21 am" src="https://cloud.githubusercontent.com/assets/806101/26559208/11799586-4463-11e7-9b90-ef03e6133473.png">
